#pragma once

#define MK_PATTERN_SLOT_COUNT 16
#define MK_SOUND_CHANNEL_COUNT 16
#define MK_MELODIC_SOUND_COUNT 8
#define MK_DRUM_SOUND_COUNT 8
#define MK_LOADED_MELODIC_SAMPLE_COUNT 4
#define MK_LOADED_DRUM_KIT_COUNT 4
#define MK_DRUM_SLICES_PER_KIT 16

#define MK_MELODIC_SAMPLE_SLOT_BASE 0
#define MK_DRUM_SAMPLE_SLOT_BASE (MK_MELODIC_SAMPLE_SLOT_BASE + MK_LOADED_MELODIC_SAMPLE_COUNT)
#define MK_SAMPLE_SLOT_COUNT (MK_LOADED_MELODIC_SAMPLE_COUNT + (MK_LOADED_DRUM_KIT_COUNT * MK_DRUM_SLICES_PER_KIT))

#define MK_MAX_VOICES 16

#define MK_STEPS_PER_BAR 16
#define MK_MAX_BARS 16
#define MK_MAX_PATTERN_STEPS (MK_STEPS_PER_BAR * MK_MAX_BARS)

#define MK_AUDIO_CHANNELS 2
#define MK_AUDIO_BLOCK_FRAMES 64
#define MK_DEFAULT_AUDIO_SAMPLE_RATE 24000u

#define MK_TOTAL_CONTROLS 25
#define MK_TOTAL_DIRECT_BUTTONS 5
